[package]
name = "vaux-pub"
version = "0.4.1"
edition = "2021"


[dependencies]
vaux-client = {path="../vaux-client"}
vaux-mqtt = {path="../vaux-mqtt"}
clap = { version = "4.2", features = ["derive"] }

