[package]
name = "vaux-sub"
version = "0.4.2"
edition = "2021"

[dependencies]
vaux-client = { path = "../vaux-client", features = ["developer"] }
vaux-mqtt = { path = "../vaux-mqtt" }
clap = { version = "4.2", features = ["derive"] }
rustls = "0.21"
