[package]
name = "vaux-sub"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vaux-client = {path="../vaux-client"}
vaux-mqtt = {path="../vaux-mqtt"}