[package]
name = "vaux-mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-util = { version = "0.7.0", features = ["codec"] }
bytes = "1.1.0"
uuid = { version = "1.2.1", features = ["v4", "fast-rng"] }