[package]
name = "vaux-client"
version = "0.4.15"
edition = "2021"

[features]
developer = ["rustls/dangerous_configuration"]

[dependencies]
vaux-mqtt = { version = "0.4.15", path = "../vaux-mqtt" }
bytes = "1.3"
uuid = "1.0"
crossbeam-channel = "0.5.8"
rustls = { version = "0.21" }
