[package]
name = "vaux-client"
version = "0.5.0"
edition = "2021"

[features]
developer = []

[dependencies]
vaux-mqtt = { version = "0.5.0", path = "../vaux-mqtt" }
bytes = "1.8"
uuid = "1.11"
rustls = { version = "0.23" }
tokio = { version = "1.41.0", features = ["rt-multi-thread", "macros"] }
